package com.artmondo.algomodo.generators.fractals

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import com.artmondo.algomodo.core.rng.SeededRNG
import com.artmondo.algomodo.data.palettes.Palette
import com.artmondo.algomodo.generators.Generator
import com.artmondo.algomodo.generators.ParamGroup
import com.artmondo.algomodo.generators.Parameter
import com.artmondo.algomodo.generators.Quality
import kotlin.math.*

class IfsBarnsleyGenerator : Generator {

    override val id = "fractal-ifs-barnsley"
    override val family = "fractals"
    override val styleName = "IFS / Barnsley Fern"
    override val definition =
        "Iterated Function System fractals generated by stochastic application of affine transformations."
    override val algorithmNotes =
        "Starts from a seed point and repeatedly applies one of several affine transformations, " +
        "chosen randomly with weighted probabilities. After many iterations the attractor shape emerges. " +
        "The fern variation uses Barnsley's classic four-transform system. Animation applies a slow " +
        "rotation to each transform's coefficients."
    override val supportsVector = false
    override val supportsAnimation = true

    override val parameterSchema: List<Parameter> = listOf(
        Parameter.SelectParam(
            name = "Preset",
            key = "preset",
            group = ParamGroup.COMPOSITION,
            help = "Classic IFS fractals or seed-based random systems",
            options = listOf("barnsley", "sierpinski", "maple", "dragon", "tree", "spiral", "crystal", "koch", "random"),
            default = "barnsley"
        ),
        Parameter.NumberParam(
            name = "Iterations",
            key = "iterations",
            group = ParamGroup.COMPOSITION,
            help = "More iterations = denser, more detailed image",
            min = 50000f, max = 500000f, step = 50000f, default = 300000f
        ),
        Parameter.NumberParam(
            name = "Point Size",
            key = "pointSize",
            group = ParamGroup.GEOMETRY,
            help = "Size of each plotted point in pixels",
            min = 1f, max = 4f, step = 1f, default = 2f
        ),
        Parameter.NumberParam(
            name = "Rotation",
            key = "rotation",
            group = ParamGroup.GEOMETRY,
            help = "Rotate the entire fractal",
            min = 0f, max = 360f, step = 5f, default = 0f
        ),
        Parameter.SelectParam(
            name = "Color Mode",
            key = "colorMode",
            group = ParamGroup.COLOR,
            help = "flame: color by transform blending | height: by y-position | density: by point density",
            options = listOf("flame", "height", "density"),
            default = "flame"
        ),
        Parameter.NumberParam(
            name = "Speed",
            key = "speed",
            group = ParamGroup.FLOW_MOTION,
            help = "Animation rotation speed",
            min = 0.1f, max = 3.0f, step = 0.1f, default = 0.5f
        )
    )

    override fun getDefaultParams(): Map<String, Any> = mapOf(
        "preset" to "barnsley",
        "iterations" to 300000f,
        "pointSize" to 2f,
        "rotation" to 0f,
        "colorMode" to "flame",
        "speed" to 0.5f
    )

    private data class AffineTransform(
        val a: Float, val b: Float, val c: Float, val d: Float,
        val e: Float, val f: Float, val p: Float
    )

    private fun getTransforms(preset: String, anim: Float, rng: SeededRNG): List<AffineTransform> {
        val ct = cos(anim)
        val st = sin(anim)

        return when (preset) {
            "barnsley" -> listOf(
                AffineTransform(0f, 0f, 0f, 0.16f, 0f, 0f, 0.01f),
                AffineTransform(
                    0.85f, 0.04f + 0.03f * st, -0.04f + 0.03f * ct, 0.85f,
                    0f, 1.6f, 0.85f
                ),
                AffineTransform(0.2f, -0.26f, 0.23f, 0.22f, 0f, 1.6f, 0.07f),
                AffineTransform(-0.15f, 0.28f, 0.26f, 0.24f, 0f, 0.44f, 0.07f)
            )

            "sierpinski" -> {
                val r = 0.01f * st
                listOf(
                    AffineTransform(0.5f, r, -r, 0.5f, 0f, 0f, 0.333f),
                    AffineTransform(0.5f, -r, r, 0.5f, 0.5f, 0f, 0.333f),
                    AffineTransform(0.5f, 0f, 0f, 0.5f, 0.25f, 0.433f, 0.334f)
                )
            }

            "maple" -> listOf(
                AffineTransform(0.14f, 0.01f, 0f, 0.51f, -0.08f, -1.31f, 0.10f),
                AffineTransform(
                    0.43f, 0.52f + 0.03f * st, -0.45f, 0.50f,
                    1.49f, -0.75f, 0.35f
                ),
                AffineTransform(
                    0.45f, -0.49f - 0.03f * st, 0.47f, 0.47f,
                    -1.62f, -0.74f, 0.35f
                ),
                AffineTransform(0.49f, 0f, 0f, 0.51f, 0.02f, 1.62f, 0.20f)
            )

            "dragon" -> {
                val a1 = PI.toFloat() / 4f + anim * 0.05f
                val a2 = PI.toFloat() / 4f - anim * 0.05f
                val s = 1f / sqrt(2f)
                listOf(
                    AffineTransform(
                        s * cos(a1), -s * sin(a1),
                        s * sin(a1), s * cos(a1),
                        0f, 0f, 0.5f
                    ),
                    AffineTransform(
                        -s * cos(a2), -s * sin(a2),
                        s * sin(a2), -s * cos(a2),
                        1f, 0f, 0.5f
                    )
                )
            }

            "tree" -> listOf(
                AffineTransform(0f, 0f, 0f, 0.5f, 0f, 0f, 0.05f),
                AffineTransform(
                    0.42f * ct, -0.42f * st,
                    0.42f * st, 0.42f * ct,
                    0f, 0.2f, 0.40f
                ),
                AffineTransform(
                    0.42f * ct, 0.42f * st,
                    -0.42f * st, 0.42f * ct,
                    0f, 0.2f, 0.40f
                ),
                AffineTransform(0.1f, 0f, 0f, 0.1f, 0f, 0.2f, 0.15f)
            )

            "spiral" -> listOf(
                AffineTransform(
                    0.7f * ct, -0.7f * st,
                    0.7f * st, 0.7f * ct,
                    0.1f, 0.1f, 0.50f
                ),
                AffineTransform(
                    0.3f * ct, 0.3f * st,
                    -0.3f * st, 0.3f * ct,
                    0.5f, 0.3f, 0.50f
                )
            )

            "crystal" -> {
                val scale = 0.333f
                val radius = 0.667f
                val transforms = mutableListOf<AffineTransform>()
                for (k in 0 until 6) {
                    val angle = k * PI.toFloat() / 3f + anim * 0.03f
                    transforms.add(
                        AffineTransform(
                            scale, 0f, 0f, scale,
                            radius * cos(angle), radius * sin(angle),
                            1f / 7f
                        )
                    )
                }
                transforms.add(AffineTransform(scale, 0f, 0f, scale, 0f, 0f, 1f / 7f))
                transforms
            }

            "koch" -> {
                val s3 = sqrt(3f) / 6f
                listOf(
                    AffineTransform(0.333f, 0f, 0f, 0.333f, 0f, 0f, 0.25f),
                    AffineTransform(
                        0.167f, -0.289f + 0.01f * st,
                        0.289f + 0.01f * ct, 0.167f,
                        0.333f, 0f, 0.25f
                    ),
                    AffineTransform(
                        0.167f, 0.289f - 0.01f * st,
                        -0.289f - 0.01f * ct, 0.167f,
                        0.5f, s3, 0.25f
                    ),
                    AffineTransform(0.333f, 0f, 0f, 0.333f, 0.667f, 0f, 0.25f)
                )
            }

            "random" -> {
                val numT = 3 + rng.integer(0, 3)
                val transforms = mutableListOf<AffineTransform>()
                for (k in 0 until numT) {
                    val angle = rng.range(0f, 2f * PI.toFloat()) + anim * 0.05f * (k + 1)
                    val scale = rng.range(0.2f, 0.55f)
                    val ca = cos(angle) * scale
                    val sa = sin(angle) * scale
                    transforms.add(
                        AffineTransform(
                            ca, -sa, sa, ca,
                            rng.range(-1f, 1f), rng.range(-1f, 1f),
                            1f / numT
                        )
                    )
                }
                transforms
            }

            else -> getTransforms("barnsley", anim, rng)
        }
    }

    override fun renderCanvas(
        canvas: Canvas,
        bitmap: Bitmap,
        params: Map<String, Any>,
        seed: Int,
        palette: Palette,
        quality: Quality,
        time: Float
    ) {
        val w = bitmap.width
        val h = bitmap.height
        val preset = (params["preset"] as? String) ?: "barnsley"
        val iterations = (params["iterations"] as? Number)?.toInt() ?: 300000
        val pointSize = (params["pointSize"] as? Number)?.toFloat() ?: 2f
        val rotation = (params["rotation"] as? Number)?.toFloat() ?: 0f
        val colorMode = (params["colorMode"] as? String) ?: "flame"
        val speed = (params["speed"] as? Number)?.toFloat() ?: 0.5f

        val scaledIterations = when (quality) {
            Quality.DRAFT -> iterations / 3
            Quality.BALANCED -> iterations
            Quality.ULTRA -> iterations * 2
        }

        val animAngle = time * speed * 0.15f
        val transformRng = SeededRNG(seed)
        val transforms = getTransforms(preset, animAngle, transformRng)

        val cumProb = FloatArray(transforms.size)
        cumProb[0] = transforms[0].p
        for (i in 1 until transforms.size) {
            cumProb[i] = cumProb[i - 1] + transforms[i].p
        }

        val rng = SeededRNG(seed + 1)
        var x = 0f
        var y = 0f

        val skip = 100.coerceAtMost(scaledIterations)

        val rotRad = rotation * PI.toFloat() / 180f
        val cosR = cos(rotRad)
        val sinR = sin(rotRad)

        val pointsX = FloatArray(scaledIterations)
        val pointsY = FloatArray(scaledIterations)
        val pointTransform = IntArray(scaledIterations)

        for (i in 0 until scaledIterations) {
            val r = rng.random()
            var tIdx = 0
            for (j in cumProb.indices) {
                if (r <= cumProb[j]) {
                    tIdx = j
                    break
                }
            }

            val t = transforms[tIdx]
            val nx = t.a * x + t.b * y + t.e
            val ny = t.c * x + t.d * y + t.f
            x = nx
            y = ny

            pointsX[i] = x * cosR - y * sinR
            pointsY[i] = x * sinR + y * cosR
            pointTransform[i] = tIdx
        }

        // Compute bounds
        var minX = Float.MAX_VALUE
        var maxX = -Float.MAX_VALUE
        var minY = Float.MAX_VALUE
        var maxY = -Float.MAX_VALUE
        for (i in skip until scaledIterations) {
            if (pointsX[i] < minX) minX = pointsX[i]
            if (pointsX[i] > maxX) maxX = pointsX[i]
            if (pointsY[i] < minY) minY = pointsY[i]
            if (pointsY[i] > maxY) maxY = pointsY[i]
        }

        val rangeX = (maxX - minX).coerceAtLeast(0.001f)
        val rangeY = (maxY - minY).coerceAtLeast(0.001f)
        val margin = 0.05f

        val pixels = IntArray(w * h)
        val paletteColors = palette.colorInts()
        val ptSizeInt = pointSize.roundToInt().coerceAtLeast(1) - 1
        val singlePixel = ptSizeInt == 0

        // Precompute palette LUT for density and height modes
        val lutSize = 256
        val paletteLut = IntArray(lutSize) { palette.lerpColor(it.toFloat() / (lutSize - 1)) }

        when (colorMode) {
            "density" -> {
                val histogram = IntArray(w * h)

                for (i in skip until scaledIterations) {
                    val sx = ((pointsX[i] - minX) / rangeX * (1f - 2f * margin) + margin) * w
                    val sy = (1f - ((pointsY[i] - minY) / rangeY * (1f - 2f * margin) + margin)) * h
                    val px = sx.roundToInt()
                    val py = sy.roundToInt()

                    if (singlePixel) {
                        if (px in 0 until w && py in 0 until h) {
                            histogram[py * w + px]++
                        }
                    } else {
                        for (dy in -ptSizeInt..ptSizeInt) {
                            for (dx in -ptSizeInt..ptSizeInt) {
                                val fx = px + dx
                                val fy = py + dy
                                if (fx in 0 until w && fy in 0 until h) {
                                    histogram[fy * w + fx]++
                                }
                            }
                        }
                    }
                }

                var maxDensity = 1
                for (d in histogram) {
                    if (d > maxDensity) maxDensity = d
                }
                val logMax = ln(maxDensity.toFloat() + 1f)

                for (i in pixels.indices) {
                    if (histogram[i] > 0) {
                        val t = (ln(histogram[i].toFloat() + 1f) / logMax).coerceIn(0f, 1f)
                        pixels[i] = paletteLut[(t * (lutSize - 1)).toInt().coerceIn(0, lutSize - 1)]
                    }
                }
            }

            "height" -> {
                for (i in skip until scaledIterations) {
                    val sx = ((pointsX[i] - minX) / rangeX * (1f - 2f * margin) + margin) * w
                    val sy = (1f - ((pointsY[i] - minY) / rangeY * (1f - 2f * margin) + margin)) * h
                    val px = sx.roundToInt()
                    val py = sy.roundToInt()

                    val yNorm = ((pointsY[i] - minY) / rangeY).coerceIn(0f, 1f)
                    val color = paletteLut[(yNorm * (lutSize - 1)).toInt().coerceIn(0, lutSize - 1)]

                    if (singlePixel) {
                        if (px in 0 until w && py in 0 until h) {
                            pixels[py * w + px] = color
                        }
                    } else {
                        for (dy in -ptSizeInt..ptSizeInt) {
                            for (dx in -ptSizeInt..ptSizeInt) {
                                val fx = px + dx
                                val fy = py + dy
                                if (fx in 0 until w && fy in 0 until h) {
                                    pixels[fy * w + fx] = color
                                }
                            }
                        }
                    }
                }
            }

            else -> {
                // "flame" — color by transform index
                for (i in skip until scaledIterations) {
                    val sx = ((pointsX[i] - minX) / rangeX * (1f - 2f * margin) + margin) * w
                    val sy = (1f - ((pointsY[i] - minY) / rangeY * (1f - 2f * margin) + margin)) * h
                    val px = sx.roundToInt()
                    val py = sy.roundToInt()
                    val color = paletteColors[pointTransform[i] % paletteColors.size]

                    if (singlePixel) {
                        if (px in 0 until w && py in 0 until h) {
                            pixels[py * w + px] = color
                        }
                    } else {
                        for (dy in -ptSizeInt..ptSizeInt) {
                            for (dx in -ptSizeInt..ptSizeInt) {
                                val fx = px + dx
                                val fy = py + dy
                                if (fx in 0 until w && fy in 0 until h) {
                                    pixels[fy * w + fx] = color
                                }
                            }
                        }
                    }
                }
            }
        }

        bitmap.setPixels(pixels, 0, w, 0, 0, w, h)
        canvas.drawBitmap(bitmap, 0f, 0f, null)
    }

    override fun estimateCost(params: Map<String, Any>, quality: Quality): Float {
        val iterations = (params["iterations"] as? Number)?.toInt() ?: 300000
        return (iterations / 500000f).coerceIn(0.1f, 1f)
    }
}
