package com.artmondo.algomodo.generators.geometry

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import com.artmondo.algomodo.data.palettes.Palette
import com.artmondo.algomodo.generators.Generator
import com.artmondo.algomodo.generators.ParamGroup
import com.artmondo.algomodo.generators.Parameter
import com.artmondo.algomodo.generators.Quality
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.sin

class SuperformulaGenerator : Generator {

    override val id = "geo-superformula"
    override val family = "geometry"
    override val styleName = "Superformula"
    override val definition =
        "Shapes generated by the Gielis superformula, a generalization of the superellipse producing diverse natural and geometric curves."
    override val algorithmNotes =
        "Evaluates the polar superformula r = (|cos(m*theta/4)/a|^n2 + |sin(m*theta/4)/b|^n3)^(-1/n1) " +
        "at many angle samples around the full circle. Multiple concentric layers with varying parameters " +
        "and rotational copies create complex rosette-like compositions."
    override val supportsVector = false
    override val supportsAnimation = true

    override val parameterSchema: List<Parameter> = listOf(
        Parameter.NumberParam(
            name = "Symmetry (m)",
            key = "m",
            group = ParamGroup.GEOMETRY,
            help = "m controls rotational symmetry — 3 = triangle, 4 = square, 5 = pentagon, 6 = hexagon, etc.",
            min = 1f, max = 20f, step = 1f, default = 6f
        ),
        Parameter.NumberParam(
            name = "n1",
            key = "n1",
            group = ParamGroup.GEOMETRY,
            help = "Primary exponent — large n1 = rectangle-like; n1=1 = smooth circle/polygon; small n1 = star-like",
            min = 0.1f, max = 20f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "n2",
            key = "n2",
            group = ParamGroup.GEOMETRY,
            help = "Cosine exponent — n2≠n3 breaks fore/aft symmetry",
            min = 0.1f, max = 20f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "n3",
            key = "n3",
            group = ParamGroup.GEOMETRY,
            help = "Sine exponent",
            min = 0.1f, max = 20f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "a",
            key = "a",
            group = ParamGroup.GEOMETRY,
            help = null,
            min = 0.1f, max = 4f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "b",
            key = "b",
            group = ParamGroup.GEOMETRY,
            help = null,
            min = 0.1f, max = 4f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "Layers",
            key = "layers",
            group = ParamGroup.COMPOSITION,
            help = "Concentric superformula outlines — each successive layer slightly varies n2 and n3 for organic depth",
            min = 1f, max = 6f, step = 1f, default = 2f
        ),
        Parameter.NumberParam(
            name = "Copies",
            key = "copies",
            group = ParamGroup.COMPOSITION,
            help = "Rotationally replicate the full shape stack — N evenly-spaced copies fan around the centre",
            min = 1f, max = 8f, step = 1f, default = 1f
        ),
        Parameter.SelectParam(
            name = "Color Mode",
            key = "colorMode",
            group = ParamGroup.COLOR,
            help = "layer: each concentric ring uses one palette color | gradient: color sweeps along the curve perimeter | radial: color by normalized radius",
            options = listOf("layer", "gradient", "radial"),
            default = "layer"
        ),
        Parameter.NumberParam(
            name = "Stroke Width",
            key = "strokeWidth",
            group = ParamGroup.TEXTURE,
            help = null,
            min = 0.5f, max = 8f, step = 0.5f, default = 2f
        ),
        Parameter.BooleanParam(
            name = "Fill",
            key = "fill",
            group = ParamGroup.COLOR,
            help = "Fill shape interiors with semi-transparent color",
            default = false
        ),
        Parameter.SelectParam(
            name = "3D",
            key = "enable3d",
            group = ParamGroup.GEOMETRY,
            help = "Enable 3D perspective rotation with depth effects",
            options = listOf("off", "on"),
            default = "off"
        ),
        Parameter.NumberParam(
            name = "3D Tilt",
            key = "tilt3d",
            group = ParamGroup.GEOMETRY,
            help = "Tilts the shape plane in 3D — animates as a slow Y-axis spin",
            min = 5f, max = 75f, step = 5f, default = 35f
        ),
        Parameter.NumberParam(
            name = "Depth Spread",
            key = "depthSpread",
            group = ParamGroup.GEOMETRY,
            help = "Separates layers along the Z-axis — when tilted, layers fan out like stacked plates",
            min = 0f, max = 150f, step = 5f, default = 40f
        ),
        Parameter.NumberParam(
            name = "Z Wave",
            key = "zWave",
            group = ParamGroup.GEOMETRY,
            help = "Sinusoidal Z displacement — the shape undulates in and out of the screen like a ribbon",
            min = 0f, max = 120f, step = 5f, default = 0f
        ),
        Parameter.NumberParam(
            name = "Twist",
            key = "twist",
            group = ParamGroup.GEOMETRY,
            help = "Progressive rotation as theta advances — the shape spirals through 3D space",
            min = 0f, max = 360f, step = 15f, default = 0f
        ),
        Parameter.NumberParam(
            name = "Depth Glow",
            key = "depthGlow",
            group = ParamGroup.GEOMETRY,
            help = "Stroke width and brightness modulated by depth — closer parts brighter and thicker",
            min = 0f, max = 1.0f, step = 0.1f, default = 0.5f
        ),
        Parameter.NumberParam(
            name = "Resolution",
            key = "resolution",
            group = ParamGroup.COMPOSITION,
            help = "Number of θ samples per shape — increase for high-m values",
            min = 200f, max = 4000f, step = 200f, default = 1000f
        ),
        Parameter.SelectParam(
            name = "Anim Mode",
            key = "animMode",
            group = ParamGroup.FLOW_MOTION,
            help = "spin: rotate copies | morph: n1 orbits around its set value | breathe: radius pulses per layer",
            options = listOf("spin", "morph", "breathe"),
            default = "morph"
        ),
        Parameter.NumberParam(
            name = "Speed",
            key = "speed",
            group = ParamGroup.FLOW_MOTION,
            help = null,
            min = 0.05f, max = 2f, step = 0.05f, default = 0.25f
        )
    )

    override fun getDefaultParams(): Map<String, Any> = mapOf(
        "m" to 6f,
        "n1" to 1.0f,
        "n2" to 1.0f,
        "n3" to 1.0f,
        "a" to 1.0f,
        "b" to 1.0f,
        "layers" to 2f,
        "copies" to 1f,
        "colorMode" to "layer",
        "strokeWidth" to 2f,
        "fill" to false,
        "enable3d" to "off",
        "tilt3d" to 35f,
        "depthSpread" to 40f,
        "zWave" to 0f,
        "twist" to 0f,
        "depthGlow" to 0.5f,
        "resolution" to 1000f,
        "animMode" to "morph",
        "speed" to 0.25f
    )

    private fun superformula(
        theta: Float, m: Float, n1: Float, n2: Float, n3: Float, a: Float, b: Float
    ): Float {
        val mTheta4 = m * theta / 4f
        val term1 = abs(cos(mTheta4) / a).toDouble().pow(n2.toDouble())
        val term2 = abs(sin(mTheta4) / b).toDouble().pow(n3.toDouble())
        val sum = term1 + term2
        return if (sum == 0.0) 0f else sum.pow(-1.0 / n1.toDouble()).toFloat()
    }

    @Volatile private var pxBuf: FloatArray? = null
    @Volatile private var pyBuf: FloatArray? = null
    @Volatile private var pzBuf: FloatArray? = null

    private fun ensureBuffers(n: Int) {
        if (pxBuf == null || pxBuf!!.size < n) {
            pxBuf = FloatArray(n)
            pyBuf = FloatArray(n)
            pzBuf = FloatArray(n)
        }
    }

    private fun generatePoints(
        m: Float, n1: Float, n2: Float, n3: Float, a: Float, b: Float,
        cx: Float, cy: Float, scale: Float, samples: Int, rotationOffset: Float
    ): List<Pair<Float, Float>> {
        val points = mutableListOf<Pair<Float, Float>>()
        val cosOff = cos(rotationOffset)
        val sinOff = sin(rotationOffset)
        for (i in 0..samples) {
            val theta = 2f * PI.toFloat() * i / samples
            val r = superformula(theta, m, n1, n2, n3, a, b)
            val x = scale * r * cos(theta)
            val y = scale * r * sin(theta)
            val rx = x * cosOff - y * sinOff
            val ry = x * sinOff + y * cosOff
            points.add(cx + rx to cy + ry)
        }
        return points
    }

    override fun renderCanvas(
        canvas: Canvas,
        bitmap: Bitmap,
        params: Map<String, Any>,
        seed: Int,
        palette: Palette,
        quality: Quality,
        time: Float
    ) {
        val w = bitmap.width.toFloat()
        val h = bitmap.height.toFloat()
        val m = (params["m"] as? Number)?.toFloat() ?: 6f
        val baseN1 = (params["n1"] as? Number)?.toFloat() ?: 1f
        val baseN2 = (params["n2"] as? Number)?.toFloat() ?: 1f
        val baseN3 = (params["n3"] as? Number)?.toFloat() ?: 1f
        val a = (params["a"] as? Number)?.toFloat() ?: 1f
        val b = (params["b"] as? Number)?.toFloat() ?: 1f
        val layerCount = (params["layers"] as? Number)?.toInt() ?: 2
        val copies = (params["copies"] as? Number)?.toInt() ?: 1
        val colorMode = (params["colorMode"] as? String) ?: "layer"
        val strokeWidth = (params["strokeWidth"] as? Number)?.toFloat() ?: 2f
        val fill = (params["fill"] as? Boolean) ?: false
        val baseResolution = (params["resolution"] as? Number)?.toInt() ?: 1000
        val animMode = (params["animMode"] as? String) ?: "morph"
        val speed = (params["speed"] as? Number)?.toFloat() ?: 0.25f

        canvas.drawColor(Color.BLACK)

        val cx = w / 2f
        val cy = h / 2f
        val maxR = min(w, h) * 0.4f

        // Scale resolution by quality
        val samples = when (quality) {
            Quality.DRAFT -> (baseResolution * 0.5f).toInt().coerceAtLeast(120)
            Quality.BALANCED -> baseResolution
            Quality.ULTRA -> (baseResolution * 1.5f).toInt()
        }

        val paletteColors = palette.colorInts()

        val paint = Paint().apply {
            isAntiAlias = quality != Quality.DRAFT
            strokeCap = Paint.Cap.ROUND
            strokeJoin = Paint.Join.ROUND
        }

        // Animation: compute spin rotation for copies
        val spinRotation = if (animMode == "spin") time * speed * 0.3f else 0f

        // 3D parameters
        val use3d = (params["enable3d"] as? String) == "on"
        val tilt3d = if (use3d) (params["tilt3d"] as? Number)?.toFloat() ?: 35f else 0f
        val depthSpread = if (use3d) (params["depthSpread"] as? Number)?.toFloat() ?: 40f else 0f
        val zWave = if (use3d) (params["zWave"] as? Number)?.toFloat() ?: 0f else 0f
        val twistDeg = if (use3d) (params["twist"] as? Number)?.toFloat() ?: 0f else 0f
        val twistRad = twistDeg * PI.toFloat() / 180f
        val depthGlow = if (use3d) (params["depthGlow"] as? Number)?.toFloat() ?: 0.5f else 0f

        // 3D trig constants
        val tiltRad = tilt3d * PI.toFloat() / 180f
        val cosTilt = cos(tiltRad)
        val sinTilt = sin(tiltRad)
        val tPhase = time * speed
        val spin3d = if (use3d) tPhase * 2.8f else 0f
        val cosSpin = cos(spin3d)
        val sinSpin = sin(spin3d)
        val focalLen = 800f

        val path = Path()

        // Draw from back to front: outermost layers first
        for (ring in layerCount - 1 downTo 0) {
            val ringFrac = (ring + 1).toFloat() / layerCount
            val baseScale = maxR * ringFrac

            // Per-ring parameter modulation
            val ringN1: Float
            val ringN2: Float
            val ringN3: Float
            val ringScale: Float

            when (animMode) {
                "morph" -> {
                    ringN1 = baseN1 + sin(time * speed * 2f + ring * 0.5f) * baseN1 * 0.4f
                    ringN2 = baseN2 + sin(time * speed * 1.3f + ring * 0.7f) * baseN2 * 0.3f
                    ringN3 = baseN3 + cos(time * speed * 1.6f + ring * 0.4f) * baseN3 * 0.3f
                    ringScale = baseScale
                }
                "breathe" -> {
                    ringN1 = baseN1
                    ringN2 = baseN2
                    ringN3 = baseN3
                    ringScale = baseScale * (0.8f + 0.2f * sin(time * speed * 0.5f + ring * PI.toFloat() / layerCount))
                }
                else -> {
                    ringN1 = baseN1
                    ringN2 = baseN2
                    ringN3 = baseN3
                    ringScale = baseScale
                }
            }

            for (copy in 0 until copies) {
                val copyAngle = 2f * PI.toFloat() * copy / copies + spinRotation

                if (use3d) {
                    // Generate raw points centered at origin
                    val rawPoints = generatePoints(
                        m, ringN1, ringN2, ringN3, a, b,
                        0f, 0f, ringScale, samples, copyAngle
                    )
                    if (rawPoints.isEmpty()) continue

                    val n = rawPoints.size
                    ensureBuffers(n)
                    val px = pxBuf!!
                    val py = pyBuf!!
                    val pz = pzBuf!!

                    // Layer Z offset — center layers around Z=0
                    val layerZ = depthSpread * (ring.toFloat() - (layerCount - 1) * 0.5f) * 2f

                    for (i in 0 until n) {
                        var sx = rawPoints[i].first
                        var sy = rawPoints[i].second

                        // Twist: progressive rotation as theta advances
                        if (twistRad != 0f) {
                            val tw = twistRad * (i.toFloat() / max(1, n - 1))
                            val ct = cos(tw); val st = sin(tw)
                            val tx = sx * ct - sy * st
                            val ty = sx * st + sy * ct
                            sx = tx; sy = ty
                        }

                        // Z from layer separation + wave
                        var z0 = layerZ
                        if (zWave > 0f) {
                            val theta = 2f * PI.toFloat() * i / samples
                            z0 += zWave * sin(theta * 3f + tPhase * 2f + ring * 1.5f)
                        }

                        // Tilt rotation (X-axis)
                        val y3 = sy * cosTilt - z0 * sinTilt
                        val z3 = sy * sinTilt + z0 * cosTilt

                        // Spin rotation (Y-axis)
                        val x3 = sx * cosSpin + z3 * sinSpin
                        val zf = -sx * sinSpin + z3 * cosSpin

                        // Perspective projection
                        val ps = focalLen / (focalLen + zf)
                        px[i] = cx + x3 * ps
                        py[i] = cy + y3 * ps
                        pz[i] = zf
                    }

                    // Build path from projected points
                    path.reset()
                    path.moveTo(px[0], py[0])
                    for (i in 1 until n) path.lineTo(px[i], py[i])
                    path.close()

                    // Fill
                    if (fill) {
                        paint.style = Paint.Style.FILL
                        paint.color = when (colorMode) {
                            "radial" -> palette.lerpColor(ringFrac)
                            else -> paletteColors[(ring + copy) % paletteColors.size]
                        }
                        paint.alpha = (60 + ring * 25).coerceAtMost(150)
                        canvas.drawPath(path, paint)
                    }

                    // Stroke with depth glow
                    paint.style = Paint.Style.STROKE

                    if (depthGlow > 0f) {
                        val segCount = if (time > 0f) 40 else 60
                        val segLen = max(1, n / segCount)

                        for (s in 0 until segCount) {
                            val iStart = s * segLen
                            val iEnd = if (s == segCount - 1) n - 1
                                       else min(n - 1, (s + 1) * segLen)
                            if (iStart >= n) break

                            // Average Z for depth factor
                            var avgZ = 0f
                            for (i in iStart..iEnd) avgZ += pz[i]
                            avgZ /= (iEnd - iStart + 1)

                            val df = (1f - depthGlow * (avgZ / focalLen) * 3f).coerceIn(0.15f, 1.8f)

                            val baseColor = when (colorMode) {
                                "gradient" -> {
                                    val ct = ((iStart.toFloat() / n + copy.toFloat() / copies) % 1f)
                                    palette.lerpColor(ct)
                                }
                                "radial" -> palette.lerpColor(ringFrac)
                                else -> paletteColors[(ring + copy) % paletteColors.size]
                            }

                            val r = (Color.red(baseColor) * df).toInt().coerceIn(0, 255)
                            val g = (Color.green(baseColor) * df).toInt().coerceIn(0, 255)
                            val bl = (Color.blue(baseColor) * df).toInt().coerceIn(0, 255)
                            paint.color = Color.rgb(r, g, bl)
                            paint.alpha = 255
                            paint.strokeWidth = strokeWidth * df

                            val seg = Path()
                            seg.moveTo(px[iStart], py[iStart])
                            for (i in iStart + 1..iEnd) seg.lineTo(px[i], py[i])
                            canvas.drawPath(seg, paint)
                        }
                    } else {
                        // 3D without depth glow — draw whole path
                        paint.strokeWidth = strokeWidth
                        when (colorMode) {
                            "gradient" -> {
                                val segSize = (samples / (paletteColors.size * 4)).coerceAtLeast(8)
                                for (i in 0 until n - 1 step segSize) {
                                    val end = (i + segSize + 1).coerceAtMost(n)
                                    val ct = ((i.toFloat() / n + copy.toFloat() / copies) % 1f)
                                    paint.color = palette.lerpColor(ct)
                                    paint.alpha = 255
                                    val seg = Path()
                                    seg.moveTo(px[i], py[i])
                                    for (j in i + 1 until end) seg.lineTo(px[j], py[j])
                                    canvas.drawPath(seg, paint)
                                }
                            }
                            "radial" -> {
                                paint.color = palette.lerpColor(ringFrac)
                                paint.alpha = 255
                                canvas.drawPath(path, paint)
                            }
                            else -> {
                                paint.color = paletteColors[(ring + copy) % paletteColors.size]
                                paint.alpha = 255
                                canvas.drawPath(path, paint)
                            }
                        }
                    }
                } else {
                    // Non-3D: original rendering
                    val points = generatePoints(
                        m, ringN1, ringN2, ringN3, a, b,
                        cx, cy, ringScale, samples, copyAngle
                    )
                    if (points.isEmpty()) continue

                    path.reset()
                    path.moveTo(points[0].first, points[0].second)
                    for (i in 1 until points.size) {
                        path.lineTo(points[i].first, points[i].second)
                    }
                    path.close()

                    // Fill
                    if (fill) {
                        paint.style = Paint.Style.FILL
                        paint.color = when (colorMode) {
                            "radial" -> palette.lerpColor(ringFrac)
                            else -> paletteColors[(ring + copy) % paletteColors.size]
                        }
                        paint.alpha = (60 + ring * 25).coerceAtMost(150)
                        canvas.drawPath(path, paint)
                    }

                    // Stroke
                    paint.style = Paint.Style.STROKE
                    paint.strokeWidth = strokeWidth

                    when (colorMode) {
                        "layer" -> {
                            paint.color = paletteColors[(ring + copy) % paletteColors.size]
                            paint.alpha = 255
                            canvas.drawPath(path, paint)
                        }
                        "gradient" -> {
                            val segSize = (samples / (paletteColors.size * 4)).coerceAtLeast(8)
                            for (i in 0 until points.size - 1 step segSize) {
                                val end = (i + segSize + 1).coerceAtMost(points.size)
                                val t = ((i.toFloat() / points.size + copy.toFloat() / copies) % 1f)
                                paint.color = palette.lerpColor(t)
                                paint.alpha = 255
                                val seg = Path()
                                seg.moveTo(points[i].first, points[i].second)
                                for (j in i + 1 until end) {
                                    seg.lineTo(points[j].first, points[j].second)
                                }
                                canvas.drawPath(seg, paint)
                            }
                        }
                        "radial" -> {
                            paint.color = palette.lerpColor(ringFrac)
                            paint.alpha = 255
                            canvas.drawPath(path, paint)
                        }
                        else -> {
                            paint.color = paletteColors[(ring + copy) % paletteColors.size]
                            paint.alpha = 255
                            canvas.drawPath(path, paint)
                        }
                    }
                }
            }
        }
    }

    override fun estimateCost(params: Map<String, Any>, quality: Quality): Float {
        val layers = (params["layers"] as? Number)?.toInt() ?: 2
        val copies = (params["copies"] as? Number)?.toInt() ?: 1
        val resolution = (params["resolution"] as? Number)?.toInt() ?: 1000
        return (layers * copies * resolution / 10000f).coerceIn(0.2f, 1f)
    }
}
