package com.artmondo.algomodo.generators.geometry

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import com.artmondo.algomodo.data.palettes.Palette
import com.artmondo.algomodo.generators.Generator
import com.artmondo.algomodo.generators.ParamGroup
import com.artmondo.algomodo.generators.Parameter
import com.artmondo.algomodo.generators.Quality
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.sin

class SuperformulaGenerator : Generator {

    override val id = "geo-superformula"
    override val family = "geometry"
    override val styleName = "Superformula"
    override val definition =
        "Shapes generated by the Gielis superformula, a generalization of the superellipse producing diverse natural and geometric curves."
    override val algorithmNotes =
        "Evaluates the polar superformula r = (|cos(m*theta/4)/a|^n2 + |sin(m*theta/4)/b|^n3)^(-1/n1) " +
        "at many angle samples around the full circle. Multiple concentric layers with varying parameters " +
        "and rotational copies create complex rosette-like compositions."
    override val supportsVector = false
    override val supportsAnimation = true

    override val parameterSchema: List<Parameter> = listOf(
        Parameter.NumberParam(
            name = "Symmetry (m)",
            key = "m",
            group = ParamGroup.GEOMETRY,
            help = "m controls rotational symmetry — 3 = triangle, 4 = square, 5 = pentagon, 6 = hexagon, etc.",
            min = 1f, max = 20f, step = 1f, default = 6f
        ),
        Parameter.NumberParam(
            name = "n1",
            key = "n1",
            group = ParamGroup.GEOMETRY,
            help = "Primary exponent — large n1 = rectangle-like; n1=1 = smooth circle/polygon; small n1 = star-like",
            min = 0.1f, max = 20f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "n2",
            key = "n2",
            group = ParamGroup.GEOMETRY,
            help = "Cosine exponent — n2≠n3 breaks fore/aft symmetry",
            min = 0.1f, max = 20f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "n3",
            key = "n3",
            group = ParamGroup.GEOMETRY,
            help = "Sine exponent",
            min = 0.1f, max = 20f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "a",
            key = "a",
            group = ParamGroup.GEOMETRY,
            help = null,
            min = 0.1f, max = 4f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "b",
            key = "b",
            group = ParamGroup.GEOMETRY,
            help = null,
            min = 0.1f, max = 4f, step = 0.1f, default = 1.0f
        ),
        Parameter.NumberParam(
            name = "Layers",
            key = "layers",
            group = ParamGroup.COMPOSITION,
            help = "Concentric superformula outlines — each successive layer slightly varies n2 and n3 for organic depth",
            min = 1f, max = 6f, step = 1f, default = 2f
        ),
        Parameter.NumberParam(
            name = "Copies",
            key = "copies",
            group = ParamGroup.COMPOSITION,
            help = "Rotationally replicate the full shape stack — N evenly-spaced copies fan around the centre",
            min = 1f, max = 8f, step = 1f, default = 1f
        ),
        Parameter.SelectParam(
            name = "Color Mode",
            key = "colorMode",
            group = ParamGroup.COLOR,
            help = "layer: each concentric ring uses one palette color | gradient: color sweeps along the curve perimeter | radial: color by normalized radius",
            options = listOf("layer", "gradient", "radial"),
            default = "layer"
        ),
        Parameter.NumberParam(
            name = "Stroke Width",
            key = "strokeWidth",
            group = ParamGroup.TEXTURE,
            help = null,
            min = 0.5f, max = 8f, step = 0.5f, default = 2f
        ),
        Parameter.BooleanParam(
            name = "Fill",
            key = "fill",
            group = ParamGroup.COLOR,
            help = "Fill shape interiors with semi-transparent color",
            default = false
        ),
        Parameter.NumberParam(
            name = "Resolution",
            key = "resolution",
            group = ParamGroup.COMPOSITION,
            help = "Number of θ samples per shape — increase for high-m values",
            min = 200f, max = 4000f, step = 200f, default = 1000f
        ),
        Parameter.SelectParam(
            name = "Anim Mode",
            key = "animMode",
            group = ParamGroup.FLOW_MOTION,
            help = "spin: rotate copies | morph: n1 orbits around its set value | breathe: radius pulses per layer",
            options = listOf("spin", "morph", "breathe"),
            default = "morph"
        ),
        Parameter.NumberParam(
            name = "Speed",
            key = "speed",
            group = ParamGroup.FLOW_MOTION,
            help = null,
            min = 0.05f, max = 2f, step = 0.05f, default = 0.25f
        )
    )

    override fun getDefaultParams(): Map<String, Any> = mapOf(
        "m" to 6f,
        "n1" to 1.0f,
        "n2" to 1.0f,
        "n3" to 1.0f,
        "a" to 1.0f,
        "b" to 1.0f,
        "layers" to 2f,
        "copies" to 1f,
        "colorMode" to "layer",
        "strokeWidth" to 2f,
        "fill" to false,
        "resolution" to 1000f,
        "animMode" to "morph",
        "speed" to 0.25f
    )

    private fun superformula(
        theta: Float, m: Float, n1: Float, n2: Float, n3: Float, a: Float, b: Float
    ): Float {
        val mTheta4 = m * theta / 4f
        val term1 = abs(cos(mTheta4) / a).toDouble().pow(n2.toDouble())
        val term2 = abs(sin(mTheta4) / b).toDouble().pow(n3.toDouble())
        val sum = term1 + term2
        return if (sum == 0.0) 0f else sum.pow(-1.0 / n1.toDouble()).toFloat()
    }

    private fun generatePoints(
        m: Float, n1: Float, n2: Float, n3: Float, a: Float, b: Float,
        cx: Float, cy: Float, scale: Float, samples: Int, rotationOffset: Float
    ): List<Pair<Float, Float>> {
        val points = mutableListOf<Pair<Float, Float>>()
        val cosOff = cos(rotationOffset)
        val sinOff = sin(rotationOffset)
        for (i in 0..samples) {
            val theta = 2f * PI.toFloat() * i / samples
            val r = superformula(theta, m, n1, n2, n3, a, b)
            val x = scale * r * cos(theta)
            val y = scale * r * sin(theta)
            val rx = x * cosOff - y * sinOff
            val ry = x * sinOff + y * cosOff
            points.add(cx + rx to cy + ry)
        }
        return points
    }

    override fun renderCanvas(
        canvas: Canvas,
        bitmap: Bitmap,
        params: Map<String, Any>,
        seed: Int,
        palette: Palette,
        quality: Quality,
        time: Float
    ) {
        val w = bitmap.width.toFloat()
        val h = bitmap.height.toFloat()
        val m = (params["m"] as? Number)?.toFloat() ?: 6f
        val baseN1 = (params["n1"] as? Number)?.toFloat() ?: 1f
        val baseN2 = (params["n2"] as? Number)?.toFloat() ?: 1f
        val baseN3 = (params["n3"] as? Number)?.toFloat() ?: 1f
        val a = (params["a"] as? Number)?.toFloat() ?: 1f
        val b = (params["b"] as? Number)?.toFloat() ?: 1f
        val layerCount = (params["layers"] as? Number)?.toInt() ?: 2
        val copies = (params["copies"] as? Number)?.toInt() ?: 1
        val colorMode = (params["colorMode"] as? String) ?: "layer"
        val strokeWidth = (params["strokeWidth"] as? Number)?.toFloat() ?: 2f
        val fill = (params["fill"] as? Boolean) ?: false
        val baseResolution = (params["resolution"] as? Number)?.toInt() ?: 1000
        val animMode = (params["animMode"] as? String) ?: "morph"
        val speed = (params["speed"] as? Number)?.toFloat() ?: 0.25f

        canvas.drawColor(Color.BLACK)

        val cx = w / 2f
        val cy = h / 2f
        val maxR = min(w, h) * 0.4f

        // Scale resolution by quality
        val samples = when (quality) {
            Quality.DRAFT -> (baseResolution * 0.5f).toInt().coerceAtLeast(120)
            Quality.BALANCED -> baseResolution
            Quality.ULTRA -> (baseResolution * 1.5f).toInt()
        }

        val paletteColors = palette.colorInts()

        val paint = Paint().apply {
            isAntiAlias = quality != Quality.DRAFT
            strokeCap = Paint.Cap.ROUND
            strokeJoin = Paint.Join.ROUND
        }

        // Animation: compute spin rotation for copies
        val spinRotation = if (animMode == "spin") time * speed * 0.3f else 0f

        // Draw from back to front: outermost layers first
        for (ring in layerCount - 1 downTo 0) {
            val ringFrac = (ring + 1).toFloat() / layerCount
            val baseScale = maxR * ringFrac

            // Per-ring parameter modulation
            val ringN1: Float
            val ringN2: Float
            val ringN3: Float
            val ringScale: Float

            when (animMode) {
                "morph" -> {
                    ringN1 = baseN1 + sin(time * speed * 0.25f + ring * 0.5f) * 0.5f
                    ringN2 = baseN2 + sin(time * speed * 0.15f + ring * 0.7f) * 0.2f
                    ringN3 = baseN3 + cos(time * speed * 0.18f + ring * 0.4f) * 0.2f
                    ringScale = baseScale
                }
                "breathe" -> {
                    ringN1 = baseN1
                    ringN2 = baseN2
                    ringN3 = baseN3
                    ringScale = baseScale * (0.8f + 0.2f * sin(time * speed * 0.5f + ring * PI.toFloat() / layerCount))
                }
                else -> {
                    // "spin" — no parameter modulation, just rotation
                    ringN1 = baseN1
                    ringN2 = baseN2
                    ringN3 = baseN3
                    ringScale = baseScale
                }
            }

            for (copy in 0 until copies) {
                val copyAngle = 2f * PI.toFloat() * copy / copies + spinRotation

                val points = generatePoints(
                    m, ringN1, ringN2, ringN3, a, b,
                    cx, cy, ringScale, samples, copyAngle
                )

                if (points.isEmpty()) continue

                val path = Path()
                path.moveTo(points[0].first, points[0].second)
                for (i in 1 until points.size) {
                    path.lineTo(points[i].first, points[i].second)
                }
                path.close()

                // Fill
                if (fill) {
                    paint.style = Paint.Style.FILL
                    val fillColor = when (colorMode) {
                        "layer" -> paletteColors[(ring + copy) % paletteColors.size]
                        "radial" -> palette.lerpColor(ringFrac)
                        else -> paletteColors[(ring + copy) % paletteColors.size]
                    }
                    paint.color = fillColor
                    paint.alpha = (60 + ring * 25).coerceAtMost(150)
                    canvas.drawPath(path, paint)
                }

                // Stroke
                paint.style = Paint.Style.STROKE
                paint.strokeWidth = strokeWidth

                when (colorMode) {
                    "layer" -> {
                        paint.color = paletteColors[(ring + copy) % paletteColors.size]
                        paint.alpha = 255
                        canvas.drawPath(path, paint)
                    }
                    "gradient" -> {
                        // Draw segments colored along the perimeter
                        val segSize = (samples / (paletteColors.size * 4)).coerceAtLeast(8)
                        for (i in 0 until points.size - 1 step segSize) {
                            val end = (i + segSize + 1).coerceAtMost(points.size)
                            val t = ((i.toFloat() / points.size + copy.toFloat() / copies) % 1f)
                            paint.color = palette.lerpColor(t)
                            paint.alpha = 255
                            val seg = Path()
                            seg.moveTo(points[i].first, points[i].second)
                            for (j in i + 1 until end) {
                                seg.lineTo(points[j].first, points[j].second)
                            }
                            canvas.drawPath(seg, paint)
                        }
                    }
                    "radial" -> {
                        paint.color = palette.lerpColor(ringFrac)
                        paint.alpha = 255
                        canvas.drawPath(path, paint)
                    }
                    else -> {
                        paint.color = paletteColors[(ring + copy) % paletteColors.size]
                        paint.alpha = 255
                        canvas.drawPath(path, paint)
                    }
                }
            }
        }
    }

    override fun estimateCost(params: Map<String, Any>, quality: Quality): Float {
        val layers = (params["layers"] as? Number)?.toInt() ?: 2
        val copies = (params["copies"] as? Number)?.toInt() ?: 1
        val resolution = (params["resolution"] as? Number)?.toInt() ?: 1000
        return (layers * copies * resolution / 10000f).coerceIn(0.2f, 1f)
    }
}
